<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-2QDPG9I" failures="1" tests="4" name="activities.Activity2" time="0.320" errors="0" timestamp="2021-05-30T16:23:23 IST" skipped="2">
  <testcase classname="activities.Activity2" name="testCase4" time="0.005">
    <skipped/>
  </testcase> <!-- testCase4 -->
  <system-out/>
  <testcase classname="activities.Activity2" name="testCase1" time="0.020"/>
  <system-out/>
  <testcase classname="activities.Activity2" name="testCase2" time="0.295">
    <failure message="expected [black] but found [Black]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [black] but found [Black]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at activities.Activity2.testCase2(Activity2.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- testCase2 -->
  <system-out/>
  <testcase classname="activities.Activity2" name="testCase3">
    <skipped/>
  </testcase> <!-- testCase3 -->
  <system-out/>
</testsuite> <!-- activities.Activity2 -->
